# Generated by Django 2.1.5 on 2021-07-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Enter a brief description on Cariage Foundation', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/about/')),
                ('link', models.URLField()),
                ('contact_title', models.CharField(max_length=200)),
            ],
        ),
    ]
